### ISSUE TITLE
Make .source .files optional when config file specified

### ISSUE THREAD

**Issue by kp96** [jsdoc2md/jsdoc-api#8] opened 2017-04-05 12:15 UTC
When the configuration file is specified, wouldn't it be better to assume that input sources are handled? Otherwise one has to explicitly specify `files` or `source` only to be overridden by the ones in `config`.

**Comment by 75lb** [comment] 2017-04-12 10:15
duplicate of https://github.com/jsdoc2md/jsdoc-to-markdown/issues/116

**Closed by 75lb** 2017-04-12 10:15 UTC
