### ISSUE TITLE
"access" option is not working

### ISSUE THREAD

**Issue by LeoAref** [jsdoc2md/jsdoc-api#7] opened 2017-02-27 15:16 UTC
I'm using the API for parsing my source code, and sometimes I'm just interested in the *private* symbols, so I'm using the *explainSync* method like:

```js
const result = jsdoc.explainSync({
  files: [...],
  access: 'private'
});
```

But always the results are the same, either with or without `access: 'private'`

So I looked in the source-code, and I didn't see any place using the *access* option
https://github.com/jsdoc2md/jsdoc-api/blob/master/lib/jsdoc-command.js#L47
https://github.com/jsdoc2md/jsdoc-api/search?l=JavaScript&q=access&utf8=%E2%9C%93

**Comment by 75lb** [comment] 2017-02-27 15:23
the underlying jsdoc command is run [at this point](https://github.com/jsdoc2md/jsdoc-api/blob/master/lib/explain-sync.js#L31). Please inspect `jsdocArgs` - is the `access` option being correctly passed to the command?

**Comment by LeoAref** [comment] 2017-02-27 16:45
@75lb Yes, it's there
```js
[ '/Users/marefalihama/projects/doccov/node_modules/jsdoc-75lb/jsdoc.js',
  '--access',
  'private',
  '-X',
  '/Users/../projects/..js',
  ,'/Users/../projects/..js',
  ,'.....']
```

**Comment by 75lb** [comment] 2017-02-27 16:59
hmm, looks like we've found a jsdoc bug.. i reported it (https://github.com/jsdoc3/jsdoc/issues/1331), will get back to you.

**Comment by 75lb** [comment] 2017-04-20 21:31
this was the upstream comment: 

> This happens because when you set --access private, the parent namespace is omitted from the documentation, which means there's nowhere to document the member. (Where would the docs for the member appear, after all?) This is the expected behavior.

Closing as expected behaviour.

**Closed by 75lb** 2017-04-20 21:31 UTC
Labels: bug, upstream
